import js from "@eslint/js";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

/**
 * Linting for the API.
 *
 * WHY THIS EXISTS, given `tsc --strict` already runs in CI.
 * The compiler proves types line up. It says nothing about an `await` that was
 * forgotten, a promise whose rejection nobody handles, a `catch {}` that
 * swallows a provider error, or a `throw "string"`. This codebase moves money
 * on the strength of exactly those, so every rule enabled below catches a
 * defect rather than a matter of taste. Formatting is not linted at all.
 *
 * `package.json` carried a `lint` script for months with no config beside it,
 * so `npm run lint` exited with a migration error and CI never called it. A
 * script that cannot run is worse than none: it reads as coverage that is not
 * there.
 *
 * DELIBERATELY NOT `recommendedTypeChecked`.
 * That preset turns on the `no-unsafe-*` family, which reports roughly a
 * thousand times here — almost entirely inside the suites, where the HTTP
 * client returns `json: any` on purpose so a test can assert on a response
 * shape it is in the middle of pinning down. Those reports are the test style
 * working as intended, and a thousand of them would bury the fifteen findings
 * that matter. The type-aware rules that DO matter are listed individually.
 */
export default defineConfig([
  globalIgnores([
    "dist/**",
    // Generated by `prisma generate`: not ours, and enormous.
    "src/generated/**",
    "uploads/**",
  ]),

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      parserOptions: {
        /**
         * BOTH programs, because there are two: tsconfig.json builds `src` as
         * CommonJS, and tsconfig.tests.json checks `tests`/`scripts`/`prisma`
         * as ESM with the DOM lib. Naming only the first makes every file
         * outside `src` a parse error — 55 of them, which is how the missing
         * test typecheck was found.
         */
        project: ["./tsconfig.json", "./tsconfig.tests.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },

    rules: {
      /**
       * THE RULE THIS CONFIG IS FOR.
       *
       * A dropped `await` on a database write is invisible to the compiler and
       * catastrophic in a claim-then-act sequence: the provider gets called
       * before the claim commits, which is the single ordering the whole design
       * exists to prevent. Deliberate fire-and-forget is spelled `void`, which
       * this rule accepts — there are several on the notification and payout
       * reversal paths, each with a comment saying why.
       */
      "@typescript-eslint/no-floating-promises": "error",

      /** `await` on a non-promise is always a mistake, usually a missing call. */
      "@typescript-eslint/await-thenable": "error",

      /**
       * `throw "something"` loses the stack. Every error path here is expected
       * to carry one — the refund and payout code branches on `instanceof`.
       */
      "@typescript-eslint/only-throw-error": "error",

      /**
       * A swallowed error on a provider call is how "the money moved but we
       * think it didn't" happens. An empty catch has to be written as one.
       */
      "no-empty": ["error", { allowEmptyCatch: false }],

      /**
       * A missing `break` in the webhook dispatch would route the wrong event.
       *
       * `allowEmptyCase` because grouped labels are how the Stripe intent
       * statuses are mapped — `requires_action`, `processing` and
       * `requires_capture` all mean "pending" and share one return. Those cases
       * are empty and the control flow is correct; without this the rule
       * objects to a clarifying comment sitting between two labels, which is
       * a formatting opinion rather than a defect.
       */
      "no-fallthrough": ["error", { allowEmptyCase: true }],

      /**
       * Unused values are usually a rename that half-landed. Leading underscore
       * is the escape hatch, which Express handlers need constantly
       * (`(_req, res)`).
       */
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      /**
       * `any` is load-bearing in the suites and a smell in `src`. Rather than
       * two configs, it is a warning everywhere and the ceiling below is what
       * stops it spreading.
       */
      "@typescript-eslint/no-explicit-any": "warn",

      /**
       * DOWNGRADED WITH A CEILING, not disabled — the same treatment, for the
       * same reason, as `react-hooks/set-state-in-effect` in the frontend.
       *
       * Express 4 does not await a handler, so `router.get("/x", async …)` is
       * technically a promise passed where a void function is expected: a
       * rejection escapes to an unhandled rejection rather than a 500. The rule
       * is right about the risk.
       *
       * It fires on essentially every route in the application, because that is
       * how all of them are written, and every one of them already wraps its
       * body in try/catch and answers with `fail(res, err, …)`. So the rejection
       * the rule warns about cannot currently escape — the safety is there, just
       * expressed per-handler instead of once.
       *
       * The proper fix is one `asyncHandler` wrapper applied at ~133 call sites,
       * which is a mechanical refactor with a real payoff (the try/catch in
       * every handler collapses into it) and is not something to do in the same
       * breath as introducing the linter. Left at "warn" so the count is printed
       * on every run and cannot quietly grow.
       *
       * The ceiling in `package.json` moves only with a note here:
       *
       *   186 -> 195 (buyer returns). Nine new route handlers — four for the
       *   buyer, two for the seller, two for the moderator, one eligibility
       *   read — each written the same way as the hundred and twenty-four
       *   before them. Nine handlers, nine warnings; the pattern did not get
       *   worse and no new rule was tripped.
       *
       *   195 -> 218 (placement and messaging). Twenty-three: eleven in
       *   `sellerMessaging.ts` (nine handlers plus the two path-scoped `use()`
       *   calls, whose middleware is async) and twelve in `adminPlacement.ts`.
       *   Every one is the same shape as the others, and NOTHING was added in
       *   `lib/messaging.ts`, `lib/placement.ts` or the three new suites — the
       *   libraries and tests are clean, which is the check worth making: this
       *   count growing with route handlers is expected, growing anywhere else
       *   would mean the pattern had spread.
       *
       *   The wrapper is now overdue at ~156 call sites and remains the right
       *   fix, still not to be done in the same breath as a feature.
       */
      "@typescript-eslint/no-misused-promises": "warn",

      /**
       * `async` with no `await` is usually a leftover, occasionally deliberate
       * (an interface that must return a promise). Warned, not enforced.
       */
      "@typescript-eslint/require-await": "warn",
    },
  },

  {
    // A couple of CJS requires in one-shot scripts.
    files: ["scripts/**", "prisma/**"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  {
    /**
     * `declare global { namespace Express { interface Request … } }` is the
     * only way to add `req.userId` and `req.sellerId` to Express's own types.
     * The rule's advice — prefer ES modules — cannot apply: module syntax
     * cannot reach into another package's global interface. This is the
     * documented mechanism, not a legacy habit.
     */
    files: ["src/middleware/**"],
    rules: {
      "@typescript-eslint/no-namespace": "off",
    },
  },

  {
    /**
     * Config files sit outside both tsconfig programs, so the type-aware
     * parser cannot place them and reports a parse error. They are checked by
     * the tools that read them.
     */
    files: ["*.config.mjs", "*.config.ts", "scripts/*.js"],
    ...tseslint.configs.disableTypeChecked,
  },

  {
    /**
     * One plain CommonJS script, run directly by node to mint VAPID keys.
     * Without Node's globals declared, `require` and `console` read as
     * undefined identifiers.
     */
    files: ["scripts/*.js"],
    languageOptions: {
      globals: { require: "readonly", console: "readonly", process: "readonly",
                 module: "writable", __dirname: "readonly" },
    },
  },
]);
